### ISSUE TITLE
ability to change analog rotary spin sensativity like in mame in Midnight Resistance and Heavy Barrel

### ISSUE THREAD

**Issue by konradpop** [jotego/jtcop#17]
due to various rotary joystick interfaces the response on the rotation can be slow with this game, mame has a feature for analog rotary sensitivity and speed so that the character can spin faster or slower etc. Is this possible in this, Using DaemonBite joystick with rotary interface + LS30 joysticks, the default rotation speed is too slow in the game.

**Comment by jotego** [comment]
Fixed. I will update the binary files on Friday.
